build:
  nodes:
    coverage:
      tests:
        before:
        - npm install
        - npm run build
        override:
          - 
            command: npm test
            coverage:
              file: 'tests/clover.xml'
              format: 'clover'
