language: node_js

node_js:
    - "node"
    - "11"
    - "10"

sudo: false

git:
    submodules: false

addons:  
  firefox: latest

install:  
    - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P ~/
    - tar -xzf ~/geckodriver-v0.26.0-linux64.tar.gz -C ~/
    - rm ~/geckodriver-v0.26.0-linux64.tar.gz
    - sudo mv -f ~/geckodriver /usr/local/share
    - sudo chmod +x /usr/local/share/geckodriver
    - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

before_script:
    - npm install
    - npm run build

script:
    - npm test
